### ISSUE TITLE
API signal 

### ISSUE THREAD

**Issue by NhuDoADL** [Ovarro/PhocusEnigmaApiDocs#3]
Could you please check if the API get signal working or not. In my case it always returns empty array 
For example:
https://leakvisiondata.atriumiot.com/logger/signal/529531/2023-06-01/2023-06-01/(my token here)
this is the result:
{"serial":"529531","signals":[]}

**Comment by James-Goodbourn** [comment]
HI @NhuDoADL After looking at your account, it looks like the loggers are not sending any signal values. That is why the returned array is always empty.

I would check with support.ld@ovarro.com. They will be able to assist in checking the loggers, and get to the bottom as to why they are not sending any signal values.
